targets:
  $default:
    builders:
      hive_generator:
        generate_for:
          exclude:
            - test/**
            - lib_old/**
      freezed:
        generate_for:
          exclude:
            - test/**
            - lib_old/**
      auto_route_generator:
        generate_for:
          exclude:
            - test/**
            - lib_old/**
