targets:
  $default:
    builders:
      freezed:
        generate_for:
          exclude:
            - test/**
            - lib_old/**
            - customer/**
            - driver/**
      auto_route_generator:
        generate_for:
          exclude:
            - test/**
            - lib_old/**
            - customer/**
            - driver/**
