export 'package:rokctapp/presentation/pages/main/manager/main_page.dart' show ManagerMainPage;
export 'package:rokctapp/presentation/pages/become/become_seller.dart' show CreateShopPage;
export 'package:rokctapp/presentation/pages/view_map/manager/view_map_page.dart' show ManagerViewMapPage;
export 'package:rokctapp/presentation/pages/view_map/manager/map_search_page.dart' show ManagerMapSearchPage;
export 'package:rokctapp/presentation/pages/income/manager/income_page.dart' show ManagerIncomePage;
export 'package:rokctapp/presentation/pages/main/manager/foods/foods_page.dart';
export 'package:rokctapp/presentation/pages/auth/manager/auth_page.dart' show ManagerAuthPage;
export 'package:rokctapp/presentation/pages/initial/no_connection/no_connection_page.dart' show NoConnectionPage, ManagerNoConnectionPage;
export 'package:rokctapp/presentation/pages/order_history/manager/order_history.dart' show ManagerOrderHistoryPage;
export 'package:rokctapp/presentation/pages/restaurant/manager/notification_list_page.dart' show ManagerNotificationListPage;
export 'package:rokctapp/presentation/pages/main/manager/create_order/order/order_page.dart' show ManagerOrderPage;
export 'package:rokctapp/presentation/pages/main/manager/create_order/create_order_page.dart' show ManagerCreateOrderPage;
export 'package:rokctapp/presentation/pages/restaurant/manager/delivery_zone/delivery_zone_page.dart' show ManagerDeliveryZonePage;
export 'package:rokctapp/presentation/pages/main/manager/create_order/shipping/shipping_address_page.dart';
export 'package:rokctapp/presentation/pages/main/manager/create_order/shipping/details/delivery_time_page.dart';
export 'package:rokctapp/presentation/pages/main/manager/create_order/shipping/address/select_address_page.dart';
export 'package:rokctapp/presentation/pages/main/manager/create_order/shipping/select_user/select_user_page.dart';
export 'package:rokctapp/presentation/pages/main/manager/create_order/shipping/select_section/select_section_page.dart';
export 'package:rokctapp/presentation/pages/main/manager/create_order/shipping/select_table/select_table_page.dart';
export 'package:rokctapp/presentation/pages/restaurant/manager/subscriptions/subscriptions_page.dart';
export 'package:rokctapp/presentation/components/manager/web_view_page.dart';
