// Mocks generated by Mockito 5.4.4 from annotations
// in billing_app/test/application/billing/billing_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:billing_app/infrastructure/models/data/product.dart' as _i7;
import 'package:billing_app/infrastructure/models/usecases/product_usecases.dart'
    as _i3;
import 'package:billing_app/infrastructure/repository/product_repository.dart'
    as _i2;
import 'package:billing_app/presentation/components/error/failure.dart' as _i6;
import 'package:fpdart/fpdart.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductRepository_0 extends _i1.SmartFake
    implements _i2.ProductRepository {
  _FakeProductRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetProductByBarcodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductByBarcodeUseCase extends _i1.Mock
    implements _i3.GetProductByBarcodeUseCase {
  MockGetProductByBarcodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ProductRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeProductRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.ProductRepository);

  @override
  _i4.Future<_i5.Either<_i6.Failure, _i7.Product>> call(String? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i4.Future<_i5.Either<_i6.Failure, _i7.Product>>.value(
              _i8.dummyValue<_i5.Either<_i6.Failure, _i7.Product>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i4.Future<_i5.Either<_i6.Failure, _i7.Product>>);
}
