export 'response/login_response.dart';
export 'response/products_paginate_response.dart';
export 'data/product_data.dart';
export 'response/brands_paginate_response.dart';
export 'response/single_brand_response.dart';
export 'data/brand_data.dart';
export 'response/banners_paginate_response.dart';
export 'response/shops_paginate_response.dart';
export 'data/shop_data.dart';
export 'response/addresses_response.dart';
export 'data/location.dart';
export 'data/local_address_data.dart';
export 'data/local_location.dart';
export 'response/single_shop_response.dart';
export 'response/categories_paginate_response.dart';
export 'response/single_product_response.dart';
export 'data/typed_extra.dart';
export 'response/currencies_response.dart';
export 'response/product_calculate_response.dart';
export 'data/cart_product_data.dart';
export 'data/shop_total_data.dart';
export 'response/payments_response.dart';
export 'data/deliveries_data.dart';
export 'data/order_body_data.dart';
export 'response/order_paginate_response.dart';
export 'data/currency_data.dart';
export 'data/order_data.dart';
export 'response/single_order_response.dart';
export 'response/gallery_upload_response.dart';
export 'data/review_data.dart';
export 'response/profile_response.dart';
export 'response/blogs_paginate_response.dart' hide Links, Meta;
export 'response/blog_details_response.dart';
export 'data/blog_data.dart';
export 'data/apply_coupon_data.dart';
export 'response/coupon_response.dart';
export 'data/coupon_data.dart';
export 'response/wallet_histories_response.dart';
export 'response/global_settings_response.dart';
export 'data/shop_delivery.dart';
export 'response/single_address_response.dart';
export 'data/chat_message_data.dart';
export 'response/mobile_translations_response.dart';
export 'response/languages_response.dart';
export 'response/shop_deliveries_response.dart';
export 'response/transactions_response.dart';
export 'response/create_order_response.dart';
export 'response/register_response.dart';
export 'response/verify_phone_response.dart';
export 'data/profile_data.dart';
export 'response/cashback_response.dart';
export 'data/look_like_data.dart';
export 'data/payment_data.dart';
export 'data/parcel_order.dart' hide Address;
export 'response/parcel_calculate_response.dart' hide Data;
export 'response/parcel_response.dart';
export 'data/user.dart';
export 'data/refund_data.dart';
export 'data/get_calculate_data.dart';
export 'response/branches_response.dart' hide Links, Meta;
export 'data/referral_data.dart';
export 'data/address_new_data.dart';
export 'data/story_data.dart';
export 'response/tag_response.dart' hide Data;
export 'data/cashback_model.dart';
export 'response/multi_gallery_upload_response.dart';
export 'data/category_data.dart';
export 'data/unit_data.dart';
export 'data/kitchen_data.dart';
export 'data/table_data.dart';
export 'data/table_bookings_data.dart';
export 'data/table_statistics_data.dart';
export 'data/table_model.dart';
export 'data/table_info_data.dart';
export 'data/subscriptions_data.dart';
export 'data/working_day_data.dart';
export 'data/delivery_zone_data.dart';
export 'data/push_data.dart';
export 'data/settings_data.dart';
export 'data/order_calculate_data.dart';
export 'data/bookings_data.dart';
export 'data/disable_dates.dart';
export 'data/request_model_data.dart';
export 'data/translation.dart';
export 'data/addons_data.dart';
export 'data/bonus_data.dart';
export 'data/language_data.dart';
export 'data/extras_data.dart';
export 'data/discount_data.dart';
export 'data/non_exist_payment.dart';
export 'data/maksekeskus_data.dart';
export 'request/ai_translation_request.dart';
export 'response/bookings_response.dart';
export 'response/table_info_response.dart';
export 'response/request_model_response.dart';
export 'response/extras_responses.dart';
export 'response/group_extras_response.dart';

typedef CalculateResponse = ProductCalculateResponse;
typedef OrderDetailModel = SingleOrderResponse;
typedef OrderDetailData = OrderData;



